<a href="https://colab.research.google.com/github/xdlimao/colab-notebooks/blob/main/Apostila_de_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Apostila de exercícios para Pandas (Daniel 2026-02-26)
Prepara pois preciso de uma cola por ser b u r r o.

---
@Dica: Quer trazer duas colunas, funções ou etc, provavelmente vai ser um array
# Sumário:

### Nível 1: Conhecendo os Dados (Inspeção)

- **Q1:** `df.shape` - Ver a quantidade de linhas e colunas.
- **Q2:** `df.head()` - Visualizar as primeiras linhas.
- **Q3:** `df.tail()` - Visualizar as últimas linhas.
- **Q4:** `df.info()` - Ver tipos de dados e contagem de nulos globais.
- **Q5:** `df.describe()` - Obter estatísticas descritivas (média, max, min).

### Nível 2: Seleção e Fatiamento (Indexing)

- **Q6:** `df['coluna']` - Isolar uma única coluna (Series).
- **Q7:** `df[['col1', 'col2']]` - Isolar múltiplas colunas (DataFrame).
- **Q8:** `df.iloc[0]` - Pegar uma linha específica pela posição numérica.
- **Q9:** `df.iloc[a:b]` - Fatiar (slice) um conjunto de linhas pela posição.
- **Q10:** `df.loc[]` ou `df.iloc[]` - Acessar o valor exato cruzando linha e coluna.

### Nível 3: Filtros e Buscas

- **Q11:** `df[df['col'] == 'X']` - Filtro simples de texto.
- **Q12:** `df[df['col'] >= X]` - Filtro matemático (maior/igual).
- **Q13:** Filtro simples aplicado a produtos.
- **Q14:** `(condicao1) & (condicao2)` - Filtro usando a condição "E" (ambas verdadeiras).
- **Q15:** `df['col'].isin(['A', 'B'])` - Filtro de múltiplas escolhas (condição "OU").

### Nível 4: Limpeza e Criação de Colunas

- **Q16:** `df.isna().sum()` - Contar exatamente quantos nulos existem por coluna.
- **Q17:** `df[df['col'].isna()]` - Filtrar para ver apenas as linhas com defeito.
- **Q18:** `df['col'].fillna('valor')` - Preencher um buraco com um valor específico.
- **Q19:** `df['nova'] = df['A'] * df['B']` - Criar coluna com matemática básica.
- **Q20:** Criação de coluna aplicando percentual/fórmula.

### Nível 5: Ordenação e Matemáticas Globais

- **Q21:** `df['col'].sum()` - Somar uma coluna inteira.
- **Q22:** `df['col'].mean()` - Tirar a média de uma coluna.
- **Q23:** `df['col'].unique()` - Ver quais são os valores únicos de uma categoria.
- **Q24:** `df.sort_values()` - Ordenar o DataFrame inteiro baseado em uma coluna.
- **Q25:** `df.nlargest()` - Pegar o "Top N" maiores valores rapidamente.

### Nível 6: Agrupamentos e Agregações

- **Q26:** `df['col'].value_counts()` - Contar quantas vezes cada item aparece.
- **Q27:** `df.groupby('A')['B'].sum()` - Agrupar e somar.
- **Q28:** `df.groupby('A')['B'].mean()` - Agrupar e tirar a média.
- **Q29:** `groupby().agg()` - Agrupar e aplicar múltiplas funções matemáticas de uma vez.
- **Q30:** `groupby(['A', 'B'])` - Agrupar usando duas ou mais colunas de hierarquia.

### Nível 7: Datas e Textos (Strings)

- **Q31:** `pd.to_datetime()` - Transformar texto em formato de Data real.
- **Q32:** `dt.day_name() / dt.day` - Extrair o dia/mês/ano de uma coluna de Data.
- **Q33:** `str.upper()` - Deixar textos em caixa alta.
- **Q34:** `str.replace()` - Substituir uma palavra por outra na coluna inteira.
- **Q35:** `str.startswith()` - Filtrar textos que começam com a letra 'M' usando métodos de string (str).

### Nível 8: Operações Avançadas

- **Q36:** `df.set_index()` - Transformar uma coluna no índice oficial.
- **Q37:** `pd.merge()` - Juntar duas tabelas diferentes usando uma coluna em comum (PROCV do Excel).
- **Q38:** `df.apply(lambda)` - Aplicar uma função customizada linha a linha.
- **Q39:** `pd.pivot_table()` - Criar uma tabela dinâmica (linhas x colunas).
- **Q40:** `df['col'].cumsum()` - Calcular a soma acumulada (linha a linha).

### Desafio Aula: Intervalos e Ocorrências

- **Q41/Q42:** Reforço em contagem de frequência (`value_counts` e `len`).
- **Q43:** Filtro de intervalo numérico com operadores lógicos (`>=` e `<=`).
- **Q44:** `df['col'].between(A, B)` - Método otimizado para filtrar intervalos numéricos.
- **Q45:** `.between()` aplicado para filtrar períodos de datas.
- **Q46:** Reforço em agrupamento para descobrir médias.
- **Q47:** `idxmax()` - Descobrir QUEM é o dono do maior valor (índice da maior média).
- **Q48:** Agrupamento seguido de ordenação (`sort_values()`).
- **Q49:** Cruzamento de filtro condicional complexo com contagem de linhas.
- **Q50:** Extrair apenas o valor absoluto máximo (`max()`) do resultado de um agrupamento.

### Desafio Real: Limpeza Avançada (Nulos)

- **Q51:** Diagnóstico total de dados faltantes na tabela.
- **Q52:** `df.dropna(subset=['col'])` - Deletar linha apenas se faltar dado em uma coluna crítica.
- **Q53:** Preencher buracos vazios usando a inteligência da Média da própria coluna.
- **Q54:** Preencher buracos usando dicionários (regras diferentes para colunas diferentes de uma só vez).
- **Q55:** Fluxo completo: Filtrar o dado -> Isolar a coluna de interesse -> Calcular a métrica final.

In [3]:
import pandas as pd
import numpy as np

dados = {
    'ID_Venda': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Data': ['2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09'],
    'Produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Notebook', 'Mouse', 'Monitor', 'Teclado', np.nan, 'Notebook'],
    'Categoria': ['Eletrônicos', 'Acessórios', 'Acessórios', 'Eletrônicos', 'Eletrônicos', 'Acessórios', 'Eletrônicos', 'Acessórios', 'Acessórios', 'Eletrônicos'],
    'Quantidade': [1, 5, 3, 2, 2, 4, 1, 2, 5, 1],
    'Preco_Unitario': [3500.0, 50.0, 150.0, 800.0, 3500.0, 50.0, 800.0, 150.0, 100.0, 3600.0],
    'Desconto': [0.10, 0.00, 0.05, 0.10, 0.15, 0.00, 0.00, 0.05, 0.00, 0.10]
}

df = pd.DataFrame(dados)

## Nível 1: Conhecendo os Dados (Inspeção Básica)

In [ ]:
# 1 - Qual é o formato do DataFrame (quantidade de linhas e colunas)? (Resposta: (10, 7))
df.shape

(10, 7)

In [ ]:
# 2 - Mostre as 4 primeiras linhas do DataFrame para entender a estrutura. (Resposta: DataFrame indo do ID_Venda 1 ao 4)
df.head(4)

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10

In [ ]:
# 3 - Mostre as 2 últimas linhas do DataFrame. (Resposta: DataFrame com ID_Venda 9 e 10)
df.tail(2)

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.0
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.1

In [ ]:
# 4 - Exiba um resumo das informações do DataFrame (tipos de colunas e contagem de nulos). (Resposta: Retorno com os Dtypes: int64, float64 e object)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        10 non-null     int64
 1   Data            10 non-null     object
 2   Produto         9 non-null      object
 3   Categoria       10 non-null     object
 4   Quantidade      10 non-null     int64
 5   Preco_Unitario  10 non-null     float64
 6   Desconto        10 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 692.0+ bytes

In [ ]:
# 5 - Gere as estatísticas descritivas básicas das colunas numéricas (média, max, min, etc). (Resposta: Tabela com as estatísticas, onde a quantidade máxima (max) é 5.0)
df.describe()

       ID_Venda  Quantidade  Preco_Unitario   Desconto
count  10.00000   10.000000       10.000000  10.000000
mean    5.50000    2.600000     1270.000000   0.055000
std     3.02765    1.577621     1587.135785   0.055025
min     1.00000    1.000000       50.000000   0.000000
25%     3.25000    1.250000      112.500000   0.000000
50%     5.50000    2.000000      475.000000   0.050000
75%     7.75000    3.750000     2825.000000   0.100000
max    10.00000    5.000000     3600.000000   0.150000

## Nível 2: Seleção e Fatiamento (Indexing)

In [ ]:
# 6 - Retorne apenas a coluna 'Produto' no formato Series. (Resposta: Uma Series com os nomes dos produtos, incluindo o NaN)
df["Produto"]

0    Notebook
1       Mouse
2     Teclado
3     Monitor
4    Notebook
5       Mouse
6     Monitor
7     Teclado
8         NaN
9    Notebook
Name: Produto, dtype: object

In [ ]:
# 7 - Selecione as colunas 'Produto', 'Quantidade' e 'Preco_Unitario' e retorne como um novo DataFrame. (Resposta: DataFrame com 10 linhas e 3 colunas)
df[["Produto", "Quantidade", "Preco_Unitario"]]

    Produto  Quantidade  Preco_Unitario
0  Notebook           1          3500.0
1     Mouse           5            50.0
2   Teclado           3           150.0
3   Monitor           2           800.0
4  Notebook           2          3500.0
5     Mouse           4            50.0
6   Monitor           1           800.0
7   Teclado           2           150.0
8       NaN           5           100.0
9  Notebook           1          3600.0

In [ ]:
# 8 - Selecione a primeira linha inteira do DataFrame usando a posição (iloc). (Resposta: Series com os dados do ID_Venda 1, Notebook)
df.iloc[0]

ID_Venda                    1
Data               2023-01-01
Produto              Notebook
Categoria         Eletrônicos
Quantidade                  1
Preco_Unitario         3500.0
Desconto                  0.1
Name: 0, dtype: object

In [ ]:
# 9 - Selecione da 3ª até a 5ª linha (índices 2 a 4) usando iloc. (Resposta: DataFrame com os IDs 3, 4 e 5)
df.iloc[2:5]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15

In [ ]:
# 10 - Qual é o valor específico da linha de índice 4, na coluna 'Produto'? Use um método de seleção. (Resposta: 'Notebook')
df.loc[4, "Produto"]

'Notebook'

## Nível 3: Filtros e Buscas

In [ ]:
# 11 - Crie um filtro para mostrar apenas as vendas da Categoria 'Acessórios'. (Resposta: DataFrame contendo 5 linhas)
df[df["Categoria"] == "Acessórios"]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00

In [ ]:
# 12 - Filtre as vendas onde a 'Quantidade' foi maior ou igual a 3. (Resposta: DataFrame com IDs 2, 3, 6 e 9)
df[df["Quantidade"] >= 3]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00

In [ ]:
# 13 - Quais foram as vendas de 'Notebook' (filtre pelo Produto)? (Resposta: DataFrame com IDs 1, 5 e 10)
df[df["Produto"] == "Notebook"]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10

In [ ]:
# 14 - Aplique duas condições: Quais vendas são da Categoria 'Eletrônicos' E tiveram 'Preco_Unitario' menor que 1000? (Resposta: DataFrame apenas com os Monitores, IDs 4 e 7)
df[(df["Categoria"] == "Eletrônicos") & (df["Preco_Unitario"] < 1000)]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.1
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.0

In [ ]:
# 15 - Aplique a condição OU: Filtre os registros onde o produto é 'Mouse' OU 'Teclado' usando o método isin(). (Resposta: DataFrame com IDs 2, 3, 6 e 8)
# -> isin Retorna True ou False baseado na coluna (caso especificado), se usado dentro do filtro, ele filtra as linhas

df[(df["Produto"] == "Mouse") | (df["Produto"] == "Teclado")]
# Mesma coisa
df[df["Produto"].isin(["Mouse", "Teclado"])]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05

## Nível 4: Limpeza e Transformação

In [ ]:
# 16 - Descubra se há valores nulos no DataFrame. Traga a soma de valores nulos por coluna. (Resposta: A coluna 'Produto' retornará 1, as demais 0)
df_16 = df.copy()

#O .isna() transforma os valores vazios em True (que no Python vale 1), e o .sum() soma esses números 1, resultando na contagem exata de nulos por coluna.
df_16.isna().sum(axis=0)

ID_Venda          0
Data              0
Produto           1
Categoria         0
Quantidade        0
Preco_Unitario    0
Desconto          0
dtype: int64

In [ ]:
# 17 - Selecione apenas a linha que contém o valor nulo na coluna 'Produto'. (Resposta: DataFrame mostrando apenas a linha do ID_Venda 9)
df[df["Produto"].isna()]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.0

In [ ]:
# 18 - Preencha o valor nulo da coluna 'Produto' com o texto 'Cabo USB'. Salve a alteração no próprio df. (Resposta: Ao exibir o df, o índice 8 não será mais NaN)
df_18 = df.copy()
#df_18.loc[df_18["Produto"].isna(), "Produto"] = "Cabo USB" -> Meu jeito
df_18["Produto"] = df_18["Produto"].fillna("Cabo USB")
display(df_18)

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05
8,9,2023-01-08,Cabo USB,Acessórios,5,100.0,0.00
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10

In [ ]:
# 19 - Crie uma nova coluna no DataFrame chamada 'Valor_Bruto', que é a multiplicação da 'Quantidade' pelo 'Preco_Unitario'. (Resposta: Nova coluna criada. O valor no índice 0 será 3500.0)
df_19 = df.copy()
df_19["Valor_Bruto"] = df_19["Quantidade"] * df_19["Preco_Unitario"]
df_19

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto,Valor_Bruto
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10,3500.0
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00,250.0
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05,450.0
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10,1600.0
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15,7000.0
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00,200.0
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00,800.0
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05,300.0
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00,500.0
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10,3600.0

In [ ]:
# 20 - Crie uma coluna 'Valor_Final', que aplica o desconto sobre o Valor_Bruto (Fórmula: Valor_Bruto * (1 - Desconto)). (Resposta: Nova coluna. O valor no índice 0 será 3150.0)
df_20 = df.copy()
df_20["Valor_Bruto"] = df_20["Quantidade"] * df_20["Preco_Unitario"]
df_20["Valor_Final"] = df_20["Valor_Bruto"] * (1 - df_20["Desconto"])
df_20

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto,Valor_Bruto,Valor_Final
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10,3500.0,3150.0
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00,250.0,250.0
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05,450.0,427.5
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10,1600.0,1440.0
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15,7000.0,5950.0
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00,200.0,200.0
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00,800.0,800.0
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05,300.0,285.0
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00,500.0,500.0
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10,3600.0,3240.0

## Nível 5: Ordenação e Matemáticas Básicas

In [ ]:
# 21 - Qual é a soma total da coluna 'Valor_Final'? Isso representa o faturamento. (Resposta: 16242.5)
df_21 = df.copy()
df_21["Valor_Bruto"] = df_21["Quantidade"] * df_21["Preco_Unitario"]
df_21["Valor_Final"] = df_21["Valor_Bruto"] * (1 - df_21["Desconto"])

#Pandas aceitas métodos do Python, mas use o do próprio Pandas para ser mais rápido
#sum(df_21["Valor_Final"])
df_21["Valor_Final"].sum()
#Valores do tipo np (NumPy) são a mesma coisa que o do python em relação a manipulação.
#Ele não quis dizer que é uma tupla isso => np.float64(16242.5) => É literalmente apenas 16242.2

np.float64(16242.5)

In [ ]:
# 22 - Qual foi a média de desconto aplicado nas vendas? (Resposta: 5%)
df["Desconto"].mean()

np.float64(0.05500000000000001)

In [ ]:
# 23 - Quais são as categorias únicas presentes na coluna 'Categoria'? (Resposta: array com 'Eletrônicos', 'Acessórios')
df["Categoria"].unique()

array(['Eletrônicos', 'Acessórios'], dtype=object)

In [ ]:
# 24 - Ordene o DataFrame do maior para o menor 'Valor_Final'. (Resposta: A primeira linha será o ID_Venda 5 com valor de 5950.0)
df_24 = df.copy()
df_24["Valor_Bruto"] = df_24["Quantidade"] * df_24["Preco_Unitario"]
df_24["Valor_Final"] = df_24["Valor_Bruto"] * (1 - df_24["Desconto"])
df_24 = df_24.sort_values("Valor_Final", ascending=False)
df_24

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto,Valor_Bruto,Valor_Final
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15,7000.0,5950.0
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10,3600.0,3240.0
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10,3500.0,3150.0
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10,1600.0,1440.0
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00,800.0,800.0
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00,500.0,500.0
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05,450.0,427.5
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05,300.0,285.0
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00,250.0,250.0
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00,200.0,200.0

In [ ]:
# 25 - Selecione as 3 maiores vendas baseadas no 'Valor_Final' usando a função nlargest(). (Resposta: DataFrame com IDs 5, 10 e 1)
df_25 = df.copy()
df_25["Valor_Bruto"] = df_25["Quantidade"] * df_25["Preco_Unitario"]
df_25["Valor_Final"] = df_25["Valor_Bruto"] * (1 - df_25["Desconto"])
df_25.nlargest(3, "Valor_Final")

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto,Valor_Bruto,Valor_Final
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15,7000.0,5950.0
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10,3600.0,3240.0
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10,3500.0,3150.0

## Nível 6: Agrupamentos e Agregações (Groupby)

In [ ]:
# 26 - Quantas vezes cada Produto foi vendido? Use contagem de valores (value_counts). (Resposta: Notebook: 3, Mouse: 2, Teclado: 2, Monitor: 2, Cabo USB: 1)
df.value_counts("Produto")

Produto
Notebook    3
Monitor     2
Mouse       2
Teclado     2
Name: count, dtype: int64

In [ ]:
# 27 - Agrupe o DataFrame por 'Categoria' e calcule a soma da coluna 'Quantidade'. (Resposta: Acessórios: 19, Eletrônicos: 7)
df.groupby("Categoria")["Quantidade"].sum()

Categoria
Acessórios     19
Eletrônicos     7
Name: Quantidade, dtype: int64

In [ ]:
# 28 - Agrupe por 'Produto' e encontre a média de 'Valor_Final'. (Resposta: Cabo USB: 500.0, Monitor: 1120.0, Mouse: 225.0, Notebook: 4113.333, Teclado: 356.25)
df_28 = df.copy()
df_28["Valor_Bruto"] = df_28["Quantidade"] * df_28["Preco_Unitario"]
df_28["Valor_Final"] = df_28["Valor_Bruto"] * (1 - df_28["Desconto"])

df_28.groupby("Produto")["Valor_Final"].mean()

Produto
Monitor     1120.000000
Mouse        225.000000
Notebook    4113.333333
Teclado      356.250000
Name: Valor_Final, dtype: float64

In [ ]:
# 29 - Calcule, ao mesmo tempo, a soma da 'Quantidade' e a média do 'Valor_Final' por 'Categoria', usando a função .agg(). (Resposta: DataFrame com duas colunas agregadas para Acessórios e Eletrônicos)
df_29 = df.copy()
df_29["Valor_Bruto"] = df_29["Quantidade"] * df_29["Preco_Unitario"]
df_29["Valor_Final"] = df_29["Valor_Bruto"] * (1 - df_29["Desconto"])

df_29.groupby("Categoria").agg({ 'Quantidade': 'sum', 'Valor_Final': 'mean' }) #Se for fazer sum e max por exemplo em quantidae, deixe dentro do array ["sum", "max"]

#Se fosse o abaixo, ele iria fazer media e soma de todas as linha xD
#df_29.agg({ 'Quantidade': 'sum', 'Valor_Final': 'mean' })

             Quantidade  Valor_Final
Categoria
Acessórios           19        332.5
Eletrônicos           7       2916.0

In [ ]:
# 30 - Agrupe por 'Categoria' e 'Produto' (múltiplas colunas) e mostre a soma do 'Valor_Bruto'. (Resposta: Series MultiIndex mostrando cada categoria e os respectivos produtos e faturamentos brutos)
df_30 = df.copy()
df_30["Valor_Bruto"] = df_30["Quantidade"] * df_30["Preco_Unitario"]
df_30["Valor_Final"] = df_30["Valor_Bruto"] * (1 - df_30["Desconto"])

df_30.groupby(["Categoria", "Produto"])["Valor_Bruto"].sum()

Categoria    Produto
Acessórios   Mouse         450.0
             Teclado       750.0
Eletrônicos  Monitor      2400.0
             Notebook    14100.0
Name: Valor_Bruto, dtype: float64

## Nível 7: Manipulação de Datas e Strings

In [24]:
# 31 - Observe o tipo da coluna 'Data' executando df.dtypes. Mude a coluna 'Data' do tipo Object (string) para Datetime. (Resposta: Ao dar df.dtypes, 'Data' será datetime64[ns])
df_31 = df.copy()
df_31["Data"] = pd.to_datetime(df_31["Data"], format='ISO8601')

df_31.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        10 non-null     int64
 1   Data            10 non-null     datetime64[ns]
 2   Produto         9 non-null      object
 3   Categoria       10 non-null     object
 4   Quantidade      10 non-null     int64
 5   Preco_Unitario  10 non-null     float64
 6   Desconto        10 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 692.0+ bytes

In [29]:
# 32 - Crie uma coluna chamada 'Dia_da_Semana' extraindo o nome ou número do dia da semana a partir da coluna 'Data'. (Resposta: Valores entre 0 (segunda) e 6 (domingo), ou nomes correspondentes)
df_32 = df.copy()
df_32["Data"] = pd.to_datetime(df_32["Data"], format='ISO8601')
df_32["Dia_da_Semana"] = df_32["Data"].dt.day_name()
df_32[["Data", "Dia_da_Semana"]]

        Data Dia_da_Semana
0 2023-01-01        Sunday
1 2023-01-02        Monday
2 2023-01-02        Monday
3 2023-01-03       Tuesday
4 2023-01-04     Wednesday
5 2023-01-05      Thursday
6 2023-01-06        Friday
7 2023-01-07      Saturday
8 2023-01-08        Sunday
9 2023-01-09        Monday

In [33]:
# 33 - Coloque todos os textos da coluna 'Categoria' em letras maiúsculas. (Resposta: Ex: 'ELETRÔNICOS')
df_33 = df.copy()

df_33["Categoria"] = df_33["Categoria"].str.upper()
df_33["Categoria"]

0    ELETRÔNICOS
1     ACESSÓRIOS
2     ACESSÓRIOS
3    ELETRÔNICOS
4    ELETRÔNICOS
5     ACESSÓRIOS
6    ELETRÔNICOS
7     ACESSÓRIOS
8     ACESSÓRIOS
9    ELETRÔNICOS
Name: Categoria, dtype: object

In [34]:
# 34 - Substitua a palavra 'Acessórios' por 'Complementos' na coluna 'Categoria'. (Resposta: Não haverá mais 'Acessórios' no dataset)
df_34 = df.copy()
df_34["Categoria"] = df_34["Categoria"].str.replace("Acessórios", "Complementos")
df_34

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10
1,2,2023-01-02,Mouse,Complementos,5,50.0,0.00
2,3,2023-01-02,Teclado,Complementos,3,150.0,0.05
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15
5,6,2023-01-05,Mouse,Complementos,4,50.0,0.00
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00
7,8,2023-01-07,Teclado,Complementos,2,150.0,0.05
8,9,2023-01-08,NaN,Complementos,5,100.0,0.00
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10

In [44]:
df_35 = df.copy()
df_35 = df_35.dropna(subset=["Produto"])
df_35[df_35["Produto"].str.startswith("M")]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.0
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.1
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.0
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.0

## Nível 8: Operações Avançadas (Join, Pivot, Apply)

In [46]:
# 36 - Transforme a coluna 'ID_Venda' no índice oficial do DataFrame (set_index). (Resposta: A primeira coluna exibida à esquerda será o ID, começando do 1)
df_36 = df.copy()
df_36.set_index("ID_Venda")

,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
ID_Venda,,,,,,
1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10
2,2023-01-02,Mouse,Acessórios,5,50.0,0.00
3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15
6,2023-01-05,Mouse,Acessórios,4,50.0,0.00
7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00
8,2023-01-07,Teclado,Acessórios,2,150.0,0.05
9,2023-01-08,NaN,Acessórios,5,100.0,0.00
10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10

In [51]:
# 37 - Crie este pequeno DataFrame rodando este código primeiro:
df_impostos = pd.DataFrame({'Categoria': ['ELETRÔNICOS', 'COMPLEMENTOS'], 'Imposto': [0.15, 0.05]})
# Agora faça um merge (join) do seu DataFrame original (que agora deve ter COMPLEMENTOS no lugar de Acessórios) com esse df_impostos usando a coluna 'Categoria'. (Resposta: O DataFrame ganhará uma coluna 'Imposto')
df_37 = df.copy()

df_37["Categoria"] = df_37["Categoria"].str.replace("Acessórios", "Complementos")
df_37["Categoria"] = df_37["Categoria"].str.upper()
df_37.merge(df_impostos)
df_37

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
0,1,2023-01-01,Notebook,ELETRÔNICOS,1,3500.0,0.10
1,2,2023-01-02,Mouse,COMPLEMENTOS,5,50.0,0.00
2,3,2023-01-02,Teclado,COMPLEMENTOS,3,150.0,0.05
3,4,2023-01-03,Monitor,ELETRÔNICOS,2,800.0,0.10
4,5,2023-01-04,Notebook,ELETRÔNICOS,2,3500.0,0.15
5,6,2023-01-05,Mouse,COMPLEMENTOS,4,50.0,0.00
6,7,2023-01-06,Monitor,ELETRÔNICOS,1,800.0,0.00
7,8,2023-01-07,Teclado,COMPLEMENTOS,2,150.0,0.05
8,9,2023-01-08,NaN,COMPLEMENTOS,5,100.0,0.00
9,10,2023-01-09,Notebook,ELETRÔNICOS,1,3600.0,0.10

In [56]:
# 38 - Usando a função apply e uma função lambda, crie uma coluna chamada 'Ticket_Medio_Item' que seja o 'Valor_Bruto' dividido pela 'Quantidade'. (Resposta: Nova coluna, o primeiro valor será 3500.0)
df_38 = df.copy()
df_38["Valor_Bruto"] = df_38["Quantidade"] * df_38["Preco_Unitario"]
calculo_tmi = lambda x: (x["Valor_Bruto"]/x["Quantidade"])
df_38["Ticket_Medio_Item"] = df_38.apply(calculo_tmi, axis=1)
df_38

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto,Valor_Bruto,Ticket_Medio_Item
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10,3500.0,3500.0
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00,250.0,50.0
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05,450.0,150.0
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10,1600.0,800.0
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15,7000.0,3500.0
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00,200.0,50.0
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00,800.0,800.0
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05,300.0,150.0
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00,500.0,100.0
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10,3600.0,3600.0

In [4]:
# 39 - Crie uma Tabela Dinâmica (pivot_table) onde os Índices (linhas) sejam os 'Produtos', as Colunas sejam as 'Categorias' e os Valores sejam a soma da 'Quantidade'. Preencha os valores nulos com zero (fill_value=0). (Resposta: Matriz mostrando quantidades vendidas cruzando produto e categoria).
df_39 = df.copy()
df_39["Produto"] = df_39["Produto"].fillna("Produto Desconhecido") # Preenche NaN para que não sejam ignorados no pivot_table
pivot_table_resultado = pd.pivot_table(df_39, values='Quantidade', index='Produto', columns='Categoria', aggfunc='sum', fill_value=0)
display(pivot_table_resultado)

Categoria             Acessórios  Eletrônicos
Produto
Monitor                        0            3
Mouse                          9            0
Notebook                       0            4
Produto Desconhecido           5            0
Teclado                        5            0

In [5]:
# 40 - Ordene o DataFrame original pela coluna 'Data' de forma crescente. Em seguida, crie uma coluna 'Faturamento_Acumulado' que calcula a soma acumulada (cumsum()) da coluna 'Valor_Final' linha a linha. (Resposta: A última linha dessa coluna representará o faturamento total da loja no período todo: 15842.5).
df_40 = df.copy()

# Certifica que a coluna 'Data' é do tipo datetime para ordenação correta
df_40["Data"] = pd.to_datetime(df_40["Data"])

# Calcula 'Valor_Bruto' e 'Valor_Final' se ainda não existirem
df_40["Valor_Bruto"] = df_40["Quantidade"] * df_40["Preco_Unitario"]
df_40["Valor_Final"] = df_40["Valor_Bruto"] * (1 - df_40["Desconto"])

# Ordena o DataFrame pela coluna 'Data'
df_40_ordenado = df_40.sort_values(by='Data', ascending=True)

# Calcula a soma acumulada do 'Valor_Final'
df_40_ordenado["Faturamento_Acumulado"] = df_40_ordenado["Valor_Final"].cumsum()
display(df_40_ordenado)

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto,Valor_Bruto,Valor_Final,Faturamento_Acumulado
0,1,2023-01-01,Notebook,Eletrônicos,1,3500.0,0.10,3500.0,3150.0,3150.0
1,2,2023-01-02,Mouse,Acessórios,5,50.0,0.00,250.0,250.0,3400.0
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05,450.0,427.5,3827.5
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10,1600.0,1440.0,5267.5
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15,7000.0,5950.0,11217.5
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00,200.0,200.0,11417.5
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00,800.0,800.0,12217.5
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05,300.0,285.0,12502.5
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00,500.0,500.0,13002.5
9,10,2023-01-09,Notebook,Eletrônicos,1,3600.0,0.10,3600.0,3240.0,16242.5

## Nível 9: Contagens e Ocorrências (Quantas vezes o valor X apareceu?)

In [7]:
# 41 - Quantas vezes o produto 'Monitor' apareceu na lista de vendas? (Dica: você pode filtrar apenas os monitores e usar a função len(), ou usar value_counts() na coluna toda). (Resposta: 2)
df.value_counts("Produto")["Monitor"]

np.int64(2)

In [10]:
# 42 - Usando a função value_counts() na coluna 'Quantidade', descubra quantas vezes cada volume de compra ocorreu. Qual foi a quantidade mais comum? (Resposta: As quantidades 1 e 2 apareceram 3 vezes cada).
df.value_counts("Quantidade")

Quantidade
1    3
2    3
5    2
3    1
4    1
Name: count, dtype: int64

## Nível 10: Intervalos (Coisas entre X e Y)

In [12]:
# 43 - Crie um filtro tradicional usando os operadores >= e <= para encontrar as vendas onde o 'Preco_Unitario' é maior ou igual a 100 E menor ou igual a 800. (Resposta: DataFrame com 5 linhas - os teclados, monitores e o valor nulo de 100.0)
df[(df["Preco_Unitario"] >= 100) & (df["Preco_Unitario"] <= 800)]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00

In [13]:
# 44 - Agora, faça exatamente a mesma busca da questão anterior, mas usando o método específico do Pandas para isso: .between(100, 800). O resultado deve ser idêntico! (Resposta: DataFrame com 5 linhas)
df[df["Preco_Unitario"].between(100, 800)]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
2,3,2023-01-02,Teclado,Acessórios,3,150.0,0.05
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00
7,8,2023-01-07,Teclado,Acessórios,2,150.0,0.05
8,9,2023-01-08,NaN,Acessórios,5,100.0,0.00

In [16]:
# 45 - O método .between() também funciona perfeitamente com datas! Filtre o DataFrame para trazer apenas as vendas que ocorreram entre '2023-01-03' e '2023-01-06'. (Resposta: DataFrame mostrando os IDs de Venda 4, 5, 6 e 7)
# Certificando que a coluna 'Data' é do tipo datetime
df_45 = df.copy()
df_45["Data"] = pd.to_datetime(df_45["Data"])

df_45[df_45["Data"].between("2023-01-03", "2023-01-06")]

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Desconto
3,4,2023-01-03,Monitor,Eletrônicos,2,800.0,0.10
4,5,2023-01-04,Notebook,Eletrônicos,2,3500.0,0.15
5,6,2023-01-05,Mouse,Acessórios,4,50.0,0.00
6,7,2023-01-06,Monitor,Eletrônicos,1,800.0,0.00

## Nível 11: Maiores Médias de Categorias

In [18]:
# 46 - Primeiro, vamos ver as médias de todas as categorias. Agrupe o DataFrame por 'Categoria' e calcule a média (mean()) do 'Preco_Unitario'. (Resposta: Acessórios: 100.0 | Eletrônicos: 2440.0)
df.groupby("Categoria")["Preco_Unitario"].mean()

Categoria
Acessórios      100.0
Eletrônicos    2440.0
Name: Preco_Unitario, dtype: float64

In [23]:
# 47 - Usando o código da questão anterior, adicione o método .idxmax() ao final. Isso não vai trazer o valor da média, mas sim o nome do índice (neste caso, a Categoria) que possui a maior média. Qual é a categoria? (Resposta: 'Eletrônicos')
df.groupby("Categoria")["Preco_Unitario"].mean().idxmax()

'Eletrônicos'

In [26]:
# 48 - Vamos ver a média de 'Quantidade' vendida por 'Produto'. Agrupe por 'Produto', calcule a média da 'Quantidade' e ordene do maior para o menor usando .sort_values(ascending=False). (Resposta: Mouse no topo com média 4.5, seguido por Teclado com 2.5)
df.groupby("Produto")["Quantidade"].mean().sort_values(ascending=False)

Produto
Mouse       4.500000
Teclado     2.500000
Monitor     1.500000
Notebook    1.333333
Name: Quantidade, dtype: float64

## Nível 12: Juntando Tudo (O Desafio Final da Aula)

In [37]:
# 49 - Quantas vezes ocorreu uma venda na categoria 'Acessórios' onde o 'Preco_Unitario' estava entre 100 e 500? (Dica: crie o filtro com essas duas condições e depois conte quantas linhas restaram com len()). (Resposta: 3 vezes)
df[(df["Categoria"] == "Acessórios") & df["Preco_Unitario"].between(100, 500)].value_counts("Categoria").loc["Acessórios"]

np.int64(3)

In [40]:
# 50 - Qual é o valor da maior média de 'Quantidade' entre as Categorias? (Dica: Agrupe por Categoria, calcule a média de Quantidade e, ao final, use .max() para pegar apenas o maior valor numérico resultante). (Resposta: 3.8)
df.groupby("Categoria")["Quantidade"].mean().max()

3.8

## Nível 13: Diagnosticando e Removendo Nulos (dropna)

Para as questões 51-55, vamos criar um novo DataFrame `df_clientes_exercicios` com a estrutura de dados implicada pelas perguntas, já que as colunas são diferentes do `df` anterior. Este DataFrame é construído para corresponder aos resultados esperados nas questões.

In [41]:
import pandas as pd
import numpy as np

dados_clientes = {
    'ID_Cliente': [101, 102, 103, 104, 105, 106, 107, 108],
    'Nome': ['Ana', 'Bruno', np.nan, 'Daniela', 'Eduardo', 'Fernanda', 'Gabriel', None],
    'Idade': [28, np.nan, 35, 42, np.nan, 29, 50, 31],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador', 'São Paulo', 'Curitiba', np.nan, 'São Paulo'],
    'Valor_Gasto': [150.50, 200.00, np.nan, 350.75, 100.00, np.nan, 500.00, 50.00],
    'Ultima_Compra': ['2023-10-01', '2023-10-05', np.nan, '2023-10-10', '2023-10-12', '2023-10-15', '2023-10-20', np.nan]
}

df_clientes = pd.DataFrame(dados_clientes)
print("Dataset de clientes criado com sucesso! Ele possui valores faltantes.")

Dataset de clientes criado com sucesso! Ele possui valores faltantes.

In [44]:
# 51 - O primeiro passo de toda análise real: descubra quantos valores nulos existem em cada coluna do DataFrame. (Dica: combine os métodos isna() ou isnull() com sum()). (Resposta: Nome: 2, Idade: 2, Cidade: 1, Valor_Gasto: 2, Ultima_Compra: 2)
df_clientes.isna().sum()

ID_Cliente       0
Nome             2
Idade            2
Cidade           1
Valor_Gasto      2
Ultima_Compra    2
dtype: int64

In [45]:
# 52 - Clientes sem nome não servem para o nosso sistema. Remova (drop) as linhas onde APENAS a coluna 'Nome' é nula. Salve esse resultado em uma nova variável chamada df_limpo. (Dica: use dropna(subset=[...])). (Resposta: O seu df_limpo ficará com apenas 6 linhas).
df_limpo = df_clientes.dropna(subset=["Nome"])
df_limpo

   ID_Cliente      Nome  Idade          Cidade  Valor_Gasto Ultima_Compra
0         101       Ana   28.0       São Paulo       150.50    2023-10-01
1         102     Bruno    NaN  Rio de Janeiro       200.00    2023-10-05
3         104   Daniela   42.0        Salvador       350.75    2023-10-10
4         105   Eduardo    NaN       São Paulo       100.00    2023-10-12
5         106  Fernanda   29.0        Curitiba          NaN    2023-10-15
6         107   Gabriel   50.0             NaN       500.00    2023-10-20

## Nível 14: Preenchendo Buracos (fillna)

In [50]:
# 53 - No seu df_limpo, você notará que o Bruno e o Eduardo (índices 1 e 4) não têm idade. Em vez de apagar esses clientes, preencha os valores vazios da coluna 'Idade' com a média das idades válidas que restaram no df_limpo. Salve a alteração no próprio df_limpo. (Resposta: A idade do Bruno e do Eduardo passará a ser 37.25).
df_limpo["Idade"] = df_limpo["Idade"].fillna(df_limpo["Idade"].mean())

0    28.00
1    37.25
3    42.00
4    37.25
5    29.00
6    50.00
Name: Idade, dtype: float64

In [54]:
# 54 - Ainda no df_limpo, preencha os valores faltantes de duas colunas com lógicas diferentes: tudo que for nulo em 'Valor_Gasto' deve virar 0.0 (pois a pessoa não comprou nada), e o que for nulo em 'Cidade' deve virar a string 'Não Informada'. (Resposta: A Fernanda, no índice 5, terá Valor_Gasto de 0.0. O Gabriel, no índice 6, terá a Cidade como 'Não Informada').
# Nota: Devido à remoção de linhas na questão 52, 'Fernanda' e 'Gabriel' podem não estar presentes nos índices mencionados, mas a lógica de preenchimento será aplicada aos valores nulos restantes.
df_limpo["Valor_Gasto"] = df_limpo["Valor_Gasto"].fillna(0.0)
df_limpo["Cidade"] = df_limpo["Cidade"].fillna("Não informado")
df_limpo

/tmp/ipykernel_302/356078184.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpo["Valor_Gasto"] = df_limpo["Valor_Gasto"].fillna(0.0)
/tmp/ipykernel_302/356078184.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpo["Cidade"] = df_limpo["Cidade"].fillna("Não informado")

   ID_Cliente      Nome  Idade          Cidade  Valor_Gasto Ultima_Compra
0         101       Ana   28.0       São Paulo       150.50    2023-10-01
1         102     Bruno    NaN  Rio de Janeiro       200.00    2023-10-05
3         104   Daniela   42.0        Salvador       350.75    2023-10-10
4         105   Eduardo    NaN       São Paulo       100.00    2023-10-12
5         106  Fernanda   29.0        Curitiba         0.00    2023-10-15
6         107   Gabriel   50.0   Não informado       500.00    2023-10-20

## Nível 15: O "Grand Finale" (Tudo Junto)

In [56]:
# 55 - Agora que seu df_limpo não tem mais nenhum valor nulo e está perfeitamente tratado, faça a seguinte análise: Qual é a média de 'Valor_Gasto' apenas para os clientes da cidade de 'São Paulo'? (Dica: primeiro faça o filtro pela cidade, depois isole a coluna de valor e tire a média). (Resposta: 125.25)
df_limpo.groupby("Cidade")["Valor_Gasto"].mean().loc["São Paulo"]

np.float64(125.25)

## Extra: Estatísticas de Agregação Avançadas

In [ ]:
import pandas as pd
import numpy as np

dados_rh = {
    'Departamento': ['Vendas', 'Marketing', 'TI', 'Vendas', 'Recursos Humanos', 'TI', 'Marketing', 'Vendas', 'Recursos Humanos', 'TI'],
    'Cargo': ['Gerente', 'Analista', 'Desenvolvedor', np.nan, 'Coordenador', 'Arquiteto', 'Analista', 'Vendedor', 'Especialista', 'Desenvolvedor'],
    'Salario': [7000, 4500, 8000, 5000, 6000, 9500, 4800, 3500, 5500, 8200],
    'Anos_Experiencia': [8, 3, 10, 5, 7, 12, 4, 2, 6, 9]
}

df_rh = pd.DataFrame(dados_rh)
print("DataFrame df_rh criado com sucesso:")
print(df_rh.head())

## Contagens Diferentes (count, nunique, value_counts)

In [ ]:
# 1 - Quantos funcionários preencheram a informação do 'Cargo' (valores não nulos)? Depois, descubra quantos cargos diferentes (únicos) existem na empresa no total. Use count() e nunique(). (Resposta: count: 9, nunique: 4 [Analista, Desenvolvedor, Vendedor, Gerente])

In [ ]:
# 2 - A diretoria quer saber a distribuição da equipe. Use value_counts() na coluna 'Departamento' para descobrir quantos funcionários trabalham em cada área. (Resposta: TI: 4, Vendas: 4, RH: 2)

## Extremos e Posição (max, min, mean, median)

In [ ]:
# 3 - Qual é o maior e o menor salário pago pela empresa hoje? Isole a coluna 'Salario' e use as funções max() e min(). (Resposta: max: 12000.0, min: 3500.0)

In [ ]:
# 4 - A média salarial pode ser "enganosa" se os gerentes ganharem muito mais que a base. Calcule primeiro a média (mean()) dos salários e depois calcule a mediana (median()) para ver o valor que está exatamente no meio da folha de pagamento. (Resposta: média: 6460.0, mediana: 5000.0)

## Dispersão e Fatias (std, var, quantile)

In [ ]:
# 5 - Existe uma discrepância muito grande nos Anos de Experiência dos nossos funcionários, ou eles têm perfis parecidos? Calcule o Desvio Padrão (std()) e a Variância (var()) da coluna 'Anos_Experiencia'. (Resposta: std: 3.40, var: 11.56)

In [ ]:
# 6 - Vamos dividir os salários em "fatias". Calcule o 1º quartil (25%) e o 3º quartil (75%) da coluna 'Salario' passando a lista para a função .quantile([0.25, 0.75]). Isso mostrará abaixo de qual valor estão os 25% mais mal pagos e os 25% mais bem pagos. (Resposta: 25% será 3900.0, e 75% será 9375.0)

## O "Canivete Suíço" (agg)

In [ ]:
# 7 - Crie um relatório definitivo para a diretoria financeira em uma única linha: Agrupe o df_rh por 'Departamento'. Em seguida, selecione a coluna 'Salario' e aplique a função .agg() passando a lista ['min', 'max', 'mean']. (Resposta: Uma tabela cruzando os departamentos com o piso (min), o teto (max) e a média (mean) salarial de cada setor!)